# CodeRabbit Configuration
# Documentation: https://docs.coderabbit.ai/getting-started/configuration

language: "en-US"
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  path_filters:
    - "!node_modules/**"
    - "!dist/**"
    - "!.next/**"
chat:
  enabled: true
